# permissions for end users to view cloudcostoptimizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubewise-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudcostoptimizer-viewer-role
rules:
- apiGroups:
  - optimization.dwarvesf.com
  resources:
  - cloudcostoptimizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optimization.dwarvesf.com
  resources:
  - cloudcostoptimizers/status
  verbs:
  - get
