---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.dwarvesf.com
  resources:
  - cloudcostoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.dwarvesf.com
  resources:
  - cloudcostoptimizers/finalizers
  verbs:
  - update
- apiGroups:
  - optimization.dwarvesf.com
  resources:
  - cloudcostoptimizers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - optimization.example.com
  resources:
  - cloudcostoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.example.com
  resources:
  - cloudcostoptimizers/finalizers
  verbs:
  - update
- apiGroups:
  - optimization.example.com
  resources:
  - cloudcostoptimizers/status
  verbs:
  - get
  - patch
  - update
