apiVersion: optimization.dwarvesf.com/v1alpha1
kind: CloudCostOptimizer
metadata:
  name: cloudcostoptimizer-sample
spec:
  analysisInterval: "1h"
  targets:
    - resources: ["pods"]
      namespaces: ["default", "kube-system"]
      automateOptimization: false
      ignoreResources:
        deployment: ["important-deployment", "critical-app"]
        statefulSet: ["database"]
        daemonSet: ["monitoring-agent"]
  costSavingThreshold: 10
  recommendationThreshold: 10
  oomKilledMemoryIncreasePercentage: 20
  highCPUUsageThreshold: 90
  highCPUUsageDuration: "10m"
  highCPUUsageIncreasePercentage: 20
  prometheusConfig:
    serverAddress: "http://prometheus-server.monitoring"
    historicalMetricDuration: 6h
  communication:
    discord:
      webhookURL: "https://discord.com/api/webhooks/your-webhook-url"
      botToken: "your-discord-bot-token"
  gpt:
    openAIKey: AIzaSyDd8V